apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: test
spec:
  containers:
  - image: nginx
    name: pod
    resources: 
      requests:
        cpu: 100m
        memory: 500Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
