apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: task
  name: task
spec:
  replicas: 5
  selector:
    matchLabels:
      app: task
  strategy: {}
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
      - image: busybox
        name: busybox
        env:
        - name: MY_GREETING
          valueFrom:
            configMapKeyRef:
              name: task-cm
              key: greeting
        command:
        - sh
        - -c
        - "env; sleep 300"
