apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: business-app
  name: business-app
spec:
  initContainers:
  - image: busybox
    name: configurer
    command:
    - sh 
    - -c 
    - "wget --no-check-certificate https://raw.githubusercontent.com/bmuschko/ckad-crash-course/master/exercises/03-init-container/app/config/config.json -O /usr/shared/app/config.json"
    volumeMounts:
    - name: config
      mountPath: /usr/shared/app
  containers:
  - image: bmuschko/nodejs-read-config:1.0.0
    name: web
    ports:
    - containerPort: 8080
    resources: {}
    volumeMounts:
    - name: config
      mountPath: /usr/shared/app
  volumes:
  - name: config
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
