apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: service-list
  name: service-list
  namespace: t23
spec:
  serviceAccount: t23
  containers:
  - command:
    - sh
    - -c
    - "while true; do curl -k https://kubernetes.default/api/v1/svc; sleep 2; done;"
    image: alpine/curl:3.14
    name: service-list
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
