apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lister
subjects:
- kind: ServiceAccount
  name: t23
  namespace: t23
